FROM nvidia/cuda:12.2.0-devel-ubuntu22.04
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y python3 python3-pip git gcc

WORKDIR /launch

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY job.py ./



ENTRYPOINT python3
