# syntax=docker/dockerfile:1.4

FROM nvidia/cuda:12.2.0-devel-ubuntu22.04
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y python3 python3-pip git gcc

WORKDIR /launch

COPY --link requirements.txt ./
RUN pip install -r requirements.txt

COPY --link job.py configs/ ./

ENTRYPOINT python3 job.py